version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/gym-management
      - JWT_SECRET=your_secure_jwt_secret
      - JWT_EXPIRES_IN=7d
      - QR_CODE_EXPIRY=24h
      - DEFAULT_POINTS_FOR_NEW_USER=100
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: